### ISSUE TITLE
How do you switch Cesius / Fahrenheit

### ISSUE THREAD

**Issue by WorldOfGZ** [ScR4tCh/timebox#10]
Hello
I have some difficulties to understand how do you switch Cesius / Fahrenheit ?
Could you explain it please ?

**Comment by Smanar** [comment]
Try
python timebox.py --address 11:75:58:E4:71:30 temp --color "#ff0000" for celcius
python timebox.py --address 11:75:58:E4:71:30 temp --color "#ff0000" --f for fahrenheit.

**Comment by WorldOfGZ** [comment]
Great, thank you
