### ISSUE TITLE
Can I send more animations as with the divoom app?

### ISSUE THREAD

**Issue by Chris9X9** [ScR4tCh/timebox#5]
Hi,

thank you for sharing your code.

Before I spend time testing it I would do know if I can send more animations as with the divoom app.

Thank you.

Greetings from Germany.

**Comment by bigboss97** [comment]
I have created a script for multiple images on Android. If you are interested please check this out:
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/PF6E77EL7jA/0.jpg)](http://www.youtube.com/watch?v=PF6E77EL7jA)

**Comment by ScR4tCh** [comment]
@Chris9X9 
What do you mean exactly with more animations ? The number of possible animations is surely infinite ;). The number of frames however seems to be limited. I encountered some issues when exeeding this limit. Its been a while since testing it, I'll try to review it.
